- hosts: localhost

  tasks:    
    - name: Get kubeadm tokens
      become: true
      become_user: koy
      shell: ping -c 3 google.com
      register: ping_cmd

    - name: Print 
      debug:
        msg: "{{ ping_cmd.stdout }}"

    - name: Pattern 
      set_fact: 
        pattern: '([^ ]+).*'
        
    - name: Extract hostnames using regex
      set_fact:
        google_hosts: >-
          {{
            ping_cmd.stdout_lines
            | select('search', 'bytes from')
            | map('regex_replace', '.*bytes from ([^ ]+).*', '\1')
            | list
          }}

    - name: Print first hostname
      debug:
        msg: "{{ google_hosts[0] | default('No hostname found') }}"